"""change stock

Revision ID: 39ee665f21d1
Revises: 50da1fbdc97f
Create Date: 2023-09-02 11:43:42.377216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ee665f21d1'
down_revision: Union[str, None] = '50da1fbdc97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_is_deleted'), 'brands', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_is_deleted'), 'categories', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_clients_is_active'), 'clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_clients_is_deleted'), 'clients', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_groups_is_active'), 'groups', ['is_active'], unique=False)
    op.create_index(op.f('ix_groups_is_deleted'), 'groups', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_item_photos_is_active'), 'item_photos', ['is_active'], unique=False)
    op.create_index(op.f('ix_item_photos_is_deleted'), 'item_photos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    op.create_index(op.f('ix_items_is_deleted'), 'items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_orders_is_active'), 'orders', ['is_active'], unique=False)
    op.create_index(op.f('ix_orders_is_deleted'), 'orders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shipment_docs_photos_is_active'), 'shipment_docs_photos', ['is_active'], unique=False)
    op.create_index(op.f('ix_shipment_docs_photos_is_deleted'), 'shipment_docs_photos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shipments_is_active'), 'shipments', ['is_active'], unique=False)
    op.create_index(op.f('ix_shipments_is_deleted'), 'shipments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shipments_items_is_active'), 'shipments_items', ['is_active'], unique=False)
    op.create_index(op.f('ix_shipments_items_is_deleted'), 'shipments_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shops_is_active'), 'shops', ['is_active'], unique=False)
    op.create_index(op.f('ix_shops_is_deleted'), 'shops', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sku_is_active'), 'sku', ['is_active'], unique=False)
    op.create_index(op.f('ix_sku_is_deleted'), 'sku', ['is_deleted'], unique=False)
    op.add_column('stocks', sa.Column('group_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_stocks_is_active'), 'stocks', ['is_active'], unique=False)
    op.create_index(op.f('ix_stocks_is_deleted'), 'stocks', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'stocks', 'groups', ['group_id'], ['id'])
    op.create_index(op.f('ix_user_photos_is_active'), 'user_photos', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_photos_is_deleted'), 'user_photos', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_user_photos_is_deleted'), table_name='user_photos')
    op.drop_index(op.f('ix_user_photos_is_active'), table_name='user_photos')
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_index(op.f('ix_stocks_is_deleted'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_is_active'), table_name='stocks')
    op.drop_column('stocks', 'group_id')
    op.drop_index(op.f('ix_sku_is_deleted'), table_name='sku')
    op.drop_index(op.f('ix_sku_is_active'), table_name='sku')
    op.drop_index(op.f('ix_shops_is_deleted'), table_name='shops')
    op.drop_index(op.f('ix_shops_is_active'), table_name='shops')
    op.drop_index(op.f('ix_shipments_items_is_deleted'), table_name='shipments_items')
    op.drop_index(op.f('ix_shipments_items_is_active'), table_name='shipments_items')
    op.drop_index(op.f('ix_shipments_is_deleted'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_is_active'), table_name='shipments')
    op.drop_index(op.f('ix_shipment_docs_photos_is_deleted'), table_name='shipment_docs_photos')
    op.drop_index(op.f('ix_shipment_docs_photos_is_active'), table_name='shipment_docs_photos')
    op.drop_index(op.f('ix_orders_is_deleted'), table_name='orders')
    op.drop_index(op.f('ix_orders_is_active'), table_name='orders')
    op.drop_index(op.f('ix_items_is_deleted'), table_name='items')
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_index(op.f('ix_item_photos_is_deleted'), table_name='item_photos')
    op.drop_index(op.f('ix_item_photos_is_active'), table_name='item_photos')
    op.drop_index(op.f('ix_groups_is_deleted'), table_name='groups')
    op.drop_index(op.f('ix_groups_is_active'), table_name='groups')
    op.drop_index(op.f('ix_clients_is_deleted'), table_name='clients')
    op.drop_index(op.f('ix_clients_is_active'), table_name='clients')
    op.drop_index(op.f('ix_categories_is_deleted'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_brands_is_deleted'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    # ### end Alembic commands ###
